##
#spring:
#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3305/dongbao-5.8-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
##  profiles:
##    active: dev
###mybatisplus的配置
#mybatis-plus:
#  mapper-locations:
#    - classpath*:com/zzh/dongbao/usm/mapper/xml/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
server:
  port: 8001

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/dongbao_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver