spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3305/dongbao-5.8-test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
#mybatisplus的配置
mybatis-plus:
  mapper-locations:
    - classpath*:com/zzh/dongbao/usm/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
